###
# find a CIDR block
GET https://rdap.arin.net/registry/ip/173.239.211.143
### GET request with a header
GET http://wp-test/index.php/wp-json
Accept: application/json
###
# curl -X GET -i http://yourdomain.com/wp-json/wp/v2/posts
GET http://wp-test/wp-json/wp/v2/posts
###
# curl -X GET -i http://yourdomain.com/wp-json/wp/v2/posts
POST http://wp-test/wp-json/wp/v2/posts
###
# curl -X GET http://your_wordpress_domain.com/wp-json
GET http://wp-test/wp-json


###
# Ping discourse direclut
GET http://discourse-dev.local/site/basic-info.json

###
# ping discourse
#   http://wp-test/wp-json/tiaa_wpplugin/v1/tiaa_discourse_ping?option_group=tiaa_connection
GET http://wp-test/wp-json/tiaa_wpplugin/v1/tiaa_discourse_ping?option_group=tiaa_connection

###
# curl -X POST
#  -H "Content-Type: application/json"
#  -d '{"name": "John Doe", "email": "john.doe[at]example.com", "group": "developers"}'
#  https://your-wordpress-site.com/wp-json/discourse-invite/v1/invite
POST http://wp-test/wp-json/tiaa_wpplugin/v1/invite
Content-Type: application/json

{
  "name": "John Doe",
  "email": "wer@wer.wer"
}

###
POST http://wp-test/wp-json/tiaa_wpplugin/v1/invite
Content-Type: application/json

{
"name": "John Doe",
"email": "werx@wer.wer"
}


###